version: '3'
services:
    web:
        container_name: myapp-nginx
        image: nginx:1.21.4
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
    php:
        container_name: myapp-php
        build:
            context: .
            dockerfile: php.Dockerfile
        volumes:
            - ./app:/app
    mariadb:
        container_name: myapp-db
        image: mariadb:10.7
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'myapp'
            MYSQL_PASSWORD: 'apppass'
            MYSQL_DATABASE: 'myappdb'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    mysqldata: {}

